//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "GKAchievementViewControllerDelegate.h"

@class GKAchievementViewController, NSString;

__attribute__((visibility("hidden")))
@interface AchievementWrapper : NSViewController <GKAchievementViewControllerDelegate>
{
    GKAchievementViewController *m_AchievementsView;
}

+ (void)reportProgressWithCache:(double)arg1 withIdentifier:(id)arg2 userCallback:(CDUnknownBlockType)arg3;
+ (void)reportSingleAchievement:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)reportProgress:(double)arg1 withIdentifier:(id)arg2 userCallback:(struct MonoObject *)arg3;
+ (void)loadAchievements:(struct MonoObject *)arg1;
+ (void)loadAchievementDescriptions:(struct MonoObject *)arg1;
- (void).cxx_destruct;
- (void)achievementViewControllerDidFinish:(id)arg1;
- (void)showAchievementsUI;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

