//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface KeyConfig : NSObject
{
    id m_KeyLabel;
    id m_Progress;
}

- (void).cxx_destruct;
- (id)window;
- (void)setControlName:(basic_string_1cdf7af0)arg1 isJoystick:(BOOL)arg2;
- (void)awakeFromNib;

@end

