//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "GKLeaderboardViewControllerDelegate.h"

@class GKLeaderboardViewController, NSString;

__attribute__((visibility("hidden")))
@interface LeaderboardWrapper : NSViewController <GKLeaderboardViewControllerDelegate>
{
    GKLeaderboardViewController *m_LeaderboardController;
}

+ (void)performCreateLeaderboard:(struct MonoArray *)arg1 withCallback:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (void)leaderboardViewControllerDidFinish:(id)arg1;
- (void)gameCenterViewControllerDidFinish:(id)arg1;
- (void)showLeaderboardUI:(id)arg1 withTimeScope:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

