//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoDataOutput, NSString;

__attribute__((visibility("hidden")))
@interface MyAVController : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    AVCaptureSession *_captureSession;
    AVCaptureDeviceInput *_captureInput;
    AVCaptureVideoDataOutput *_captureOutput;
    struct Mutex m_ImageBufferMutex;
    void *m_ImageBuffer;
    void *cvTextureCache;
    void *cvTextureCacheTexture;
    struct __CVBuffer *cvImageBuffer;
    unsigned long long m_Width;
    unsigned long long m_Height;
    _Bool m_IsUpdated;
    _Bool m_isFrontFacing;
}

@property(retain, nonatomic) AVCaptureDeviceInput *captureInput; // @synthesize captureInput=_captureInput;
@property(retain, nonatomic) AVCaptureVideoDataOutput *captureOutput; // @synthesize captureOutput=_captureOutput;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)stop;
- (void)pause;
- (void)start;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)setTexture:(void *)arg1;
- (_Bool)hasTexture;
- (_Bool)initCapture:(int)arg1 width:(int)arg2 height:(int)arg3 fps:(int)arg4 readable:(_Bool)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

