//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSWindowDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface PlayerWindowDelegate : NSObject <NSWindowDelegate>
{
}

- (void)windowDidChangeScreen:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)windowDidBecomeMain:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)sheetDidEndShouldQuit:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

