//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface PlayerAppDelegate : NSObject
{
    id m_AboutBox;
    id m_AboutMenuItem;
    id m_HideMenuItem;
    id m_QuitMenuItem;
    id m_FullscreenMenuItem;
    BOOL m_DidStart;
    NSTimer *m_UpdateTimer;
    NSTimer *m_ProfilerTickTimer;
    int m_TargetFrameRate;
}

- (void).cxx_destruct;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidResignActive:(id)arg1;
- (void)UpdateTimer;
- (void)UpdateProfilerTimer;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (void)ToggleFullscreen:(id)arg1;
- (BOOL)DidSendEvent:(id)arg1;
- (BOOL)ShouldCaptureEvent:(id)arg1;
- (void)UpdatePlayer;
- (void)ProfilerBackgroundTick;

@end

