//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UnicodeInputView.h"

@class NSOpenGLContext;

__attribute__((visibility("hidden")))
@interface PlayerWindowView : UnicodeInputView
{
    NSOpenGLContext *m_OpenGLContext;
    double m_ContentScaleFactor;
}

- (void).cxx_destruct;
- (void)scrollWheel:(id)arg1;
- (void)flagsChanged:(id)arg1;
- (void)keyUp:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)otherMouseUp:(id)arg1;
- (void)otherMouseDragged:(id)arg1;
- (void)otherMouseDown:(id)arg1;
- (void)rightMouseUp:(id)arg1;
- (void)rightMouseDragged:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (id)makeBackingLayer;
- (void)dealloc;
- (void)initImpl:(struct CGRect)arg1 scaleFactor:(double)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setContext:(struct _CGLContextObject *)arg1;

@end

