//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@class InputListDelegate, ScreenSelector;

__attribute__((visibility("hidden")))
@interface ScreenSelectorTableView : NSTableView
{
    ScreenSelector *_m_ScreenSelector;
    InputListDelegate *_m_InputListDelegate;
}

@property(retain, nonatomic) InputListDelegate *m_InputListDelegate; // @synthesize m_InputListDelegate=_m_InputListDelegate;
@property(retain) ScreenSelector *m_ScreenSelector; // @synthesize m_ScreenSelector=_m_ScreenSelector;
- (void).cxx_destruct;
- (void)keyDown:(id)arg1;

@end

