//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ScreenSelectorTableView;

__attribute__((visibility("hidden")))
@interface ScreenSelector : NSObject
{
    id m_OptionKey;
    id m_ScreenResolution;
    id m_Windowed;
    id m_GraphicsQuality;
    ScreenSelectorTableView *m_Input;
    struct vector<ScreenManager::Resolution, std::allocator<ScreenManager::Resolution>> *m_ResolutionList;
    _Bool m_PlayPressed;
}

- (void).cxx_destruct;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(int)arg3;
- (int)numberOfRowsInTableView:(id)arg1;
- (void)Quit:(id)arg1;
- (void)SaveAndQuit:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (id)window;
- (void)Play:(id)arg1;
- (void)Save:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)init;

@end

