//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSTextInput.h"

@class NSString, NSWindow;

__attribute__((visibility("hidden")))
@interface UnicodeInputView : NSView <NSTextInput>
{
    _Bool m_KeyEventNotHandledByInputManager;
    _Bool m_DidGenerateKeyEvent;
    _Bool m_PassEventDown;
    int m_KeyCode;
    NSString *m_MarkedText;
    NSWindow *m_TextInputForwardingWindow;
}

+ (id)getCurrentEventInputView;
+ (void)setCurrentEventInputView:(id)arg1;
- (void).cxx_destruct;
- (void)insertText:(id)arg1;
- (id)validAttributesForMarkedText;
- (void)unmarkText;
- (void)setMarkedText:(id)arg1 selectedRange:(struct _NSRange)arg2;
- (struct _NSRange)selectedRange;
- (struct _NSRange)markedRange;
- (BOOL)hasMarkedText;
- (struct CGRect)firstRectForCharacterRange:(struct _NSRange)arg1;
- (void)doCommandBySelector:(SEL)arg1;
- (long long)conversationIdentifier;
- (unsigned long long)characterIndexForPoint:(struct CGPoint)arg1;
- (id)attributedSubstringFromRange:(struct _NSRange)arg1;
- (void)keyUpImpl:(id)arg1;
- (void)keyDownImpl:(id)arg1;
- (void)keyUp:(id)arg1;
- (void)keyDown:(id)arg1;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (void)windowDidResignKey:(id)arg1;
- (void)abandonMarkedText;
- (BOOL)handleInputEventLikeWindows:(struct InputEvent *)arg1;
- (BOOL)sendInputEvent:(struct InputEvent *)arg1;
- (id)getTextInputResponder;
- (id)initWithFrame:(struct CGRect)arg1;

@end

